=== raeuber/wi2013c/Array/XML/kommunikation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT KOMMUNIKATION (TECHNOLOGIE+)>
<!ELEMENT TECHNOLOGIE (SPRACHE, DATEN)>
<!ELEMENT SPRACHE (HERSTELLER*)>
<!ELEMENT HERSTELLER (MODELL)>
<!ELEMENT MODELL (#PCDATA)>
<!ELEMENT DATEN (FABRIKANT)>
<!ELEMENT FABRIKANT (PRODUKT)>
<!ELEMENT PRODUKT (#PCDATA)>
<!ATTLIST TECHNOLOGIE art CDATA #REQUIRED>
<!ATTLIST HERSTELLER name CDATA #REQUIRED
					id ID #REQUIRED>
<!ATTLIST MODELL artikelnummer CDATA #REQUIRED>
<!ATTLIST FABRIKANT name CDATA #REQUIRED
					id ID #REQUIRED>
<!ATTLIST PRODUKT id ID #REQUIRED>

=== raeuber/wi2013c/Array/XML/kommunikation.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE KOMMUNIKATION SYSTEM "kommunikation.dtd">
<KOMMUNIKATION>
	<TECHNOLOGIE art="Handy">
		<SPRACHE>
			<HERSTELLER name="Samsung" id="smg">
				<MODELL artikelnummer="_01231234798">S3</MODELL>
			</HERSTELLER>
			<HERSTELLER name="Apple" id="apl">
				<MODELL artikelnummer="_02132111">Iphone5s</MODELL>
			</HERSTELLER>
		</SPRACHE> 
		<DATEN>
			<FABRIKANT name="Foxconn" id="fox">
				<PRODUKT id="_01">Mainboard</PRODUKT>
			</FABRIKANT>
		</DATEN>
	</TECHNOLOGIE>
</KOMMUNIKATION>
