=== raeuber/wi2013c/Array/XML/transportmittel.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Transportmittel(Land, Wasser, Luft)>
<!ELEMENT Land (Strasse, Feld)>
<!ELEMENT Strasse (#PCDATA)>
<!ELEMENT Feld (#PCDATA)>
<!ELEMENT Wasser (Meer, Fluss)>
<!ELEMENT Meer (#PCDATA)>
<!ELEMENT Fluss (#PCDATA)>
<!ELEMENT Luft (Kontinental, Interkontinental)>
<!ELEMENT Kontinental (#PCDATA)>
<!ELEMENT Interkontonental (#PCDATA)>

=== raeuber/wi2013c/Array/XML/Transportmittel.xml
<?xml version="1.0" standalone "no"?>
	<!DOCTYPE Transportmittel SYSTEM "Transportmittel.dtd">
	<Transportmittel>
		<Land>
			<Strasse> LKW </Strasse>
			<Feld> Traktor</Feld>
		</Land>
		<Wasser> 
			<Meer> Hochseeschiff </Meer>
			<Fluss> Schlepper </Fluss>
		</Wasser>
		<Luft>
			<Kontinental> Propellerflugzeug </Kontinental>
			<internkontinental>Airbus</interkontinental>
		</Luft>
	</Transportmittel>
